language: objective-c
osx_image: xcode8

script:
    - xcodebuild clean test -project ContactBrowser.xcodeproj -scheme ContactBrowser -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7,OS=10.0" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

after_success:
    - bash <(curl -s https://codecov.io/bash)
    - sleep 5
