language: objective-c
osx_image: xcode8

env:
    matrix:
        - TARGET='-scheme ContactBrowser -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7"'

script:
- xcodebuild -version
- set -o pipefail
- xcodebuild clean test -project ContactBrowser.xcodeproj $TARGET ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

after_success:
- bash <(curl -s https://codecov.io/bash) -J 'ContactBrowser'
