language: objective-c
osx_image: xcode8

script:
- xcodebuild clean build test -project ContactBrowser.xcodeproj -scheme ContactBrowser GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
- bash <(curl -s https://codecov.io/bash)
